import type { PumpToken, SmartWallet, PortfolioPosition, AutoStrategy, Alert } from '@/types'

export const MOCK_TOKENS: PumpToken[] = [
  {
    mint: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
    name: 'Popcat',
    symbol: 'POPCAT',
    image: 'https://pump.mypinata.cloud/ipfs/QmXs7xJzJzJzJzJzJzJzJzJzJzJzJzJzJzJzJzJzJzJz',
    marketCap: 1_240_000,
    bondingCurvePercent: 87,
    holders: 4821,
    volume24h: 890_000,
    signalScore: 28,
    aiRiskScore: 28,
    momentumScore: 92,
    whaleActivity: 'high',
    launchedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    priceUsd: 0.00124,
    priceChange24h: 34.2,
    liquidity: 420_000,
  },
  {
    mint: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    name: 'Bonk AI',
    symbol: 'BONKAI',
    image: 'https://pump.mypinata.cloud/ipfs/QmBonkAiTokenImage',
    marketCap: 340_000,
    bondingCurvePercent: 62,
    holders: 1204,
    volume24h: 210_000,
    signalScore: 45,
    aiRiskScore: 45,
    momentumScore: 78,
    whaleActivity: 'medium',
    launchedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    priceUsd: 0.00034,
    priceChange24h: 12.8,
    liquidity: 89_000,
  },
  {
    mint: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
    name: 'Wif Derivative',
    symbol: 'WIFD',
    image: 'https://pump.mypinata.cloud/ipfs/QmWifDerivative',
    marketCap: 89_000,
    bondingCurvePercent: 34,
    holders: 412,
    volume24h: 45_000,
    signalScore: 72,
    aiRiskScore: 72,
    momentumScore: 41,
    whaleActivity: 'low',
    launchedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    priceUsd: 0.000089,
    priceChange24h: -8.4,
    liquidity: 12_000,
  },
  {
    mint: 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    name: 'Sol Pepe',
    symbol: 'SPEPE',
    image: 'https://pump.mypinata.cloud/ipfs/QmSolPepe',
    marketCap: 560_000,
    bondingCurvePercent: 71,
    holders: 2890,
    volume24h: 380_000,
    signalScore: 38,
    aiRiskScore: 38,
    momentumScore: 85,
    whaleActivity: 'high',
    launchedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    priceUsd: 0.00056,
    priceChange24h: 22.1,
    liquidity: 156_000,
  },
  {
    mint: 'HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3',
    name: 'Phronis Test',
    symbol: 'PHRN',
    image: 'https://pump.mypinata.cloud/ipfs/QmPhronis',
    marketCap: 12_400,
    bondingCurvePercent: 18,
    holders: 89,
    volume24h: 8_200,
    signalScore: 91,
    aiRiskScore: 91,
    momentumScore: 22,
    whaleActivity: 'low',
    launchedAt: new Date(Date.now() - 600000).toISOString(),
    priceUsd: 0.0000124,
    priceChange24h: 156.3,
    liquidity: 3_400,
  },
]

export const MOCK_WALLETS: SmartWallet[] = [
  {
    address: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    label: 'Solana God',
    pnl24h: 42_300,
    pnl7d: 189_000,
    roi30d: 340,
    winRate: 78,
    recentBuys: 12,
    recentSells: 4,
    followers: 2840,
    tier: 'elite',
  },
  {
    address: 'HN7cABqLq46Es1jh92dQQisAq662SmxELLLwHegyk11B',
    label: 'Meme Sniper',
    pnl24h: 18_900,
    pnl7d: 67_200,
    roi30d: 210,
    winRate: 65,
    recentBuys: 28,
    recentSells: 19,
    followers: 1204,
    tier: 'pro',
  },
  {
    address: '5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1',
    label: 'Curve Hunter',
    pnl24h: 8_400,
    pnl7d: 31_000,
    roi30d: 95,
    winRate: 58,
    recentBuys: 15,
    recentSells: 11,
    followers: 456,
    tier: 'rising',
  },
]

export const MOCK_PORTFOLIO: PortfolioPosition[] = [
  {
    mint: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
    symbol: 'POPCAT',
    name: 'Popcat',
    image: MOCK_TOKENS[0].image,
    amount: 1_200_000,
    avgEntry: 0.00089,
    currentPrice: 0.00124,
    pnl: 420,
    pnlPercent: 39.3,
  },
]

export const MOCK_STRATEGIES: AutoStrategy[] = [
  {
    id: '1',
    name: 'Early Curve Sniper',
    description: 'Buy tokens at 20-40% bonding curve with low risk score',
    status: 'active',
    pnl: 12_400,
    trades: 47,
    winRate: 72,
  },
  {
    id: '2',
    name: 'Smart Money Mirror',
    description: 'Copy elite wallet buys within 30s',
    status: 'active',
    pnl: 8_900,
    trades: 23,
    winRate: 65,
  },
  {
    id: '3',
    name: 'Rug Shield Exit',
    description: 'Auto-sell on risk score spike above 75',
    status: 'paused',
    pnl: 2_100,
    trades: 12,
    winRate: 83,
  },
]

export const MOCK_ALERTS: Alert[] = [
  {
    id: '1',
    type: 'whale',
    title: 'Whale Buy Detected',
    message: 'POPCAT: 45 SOL buy from elite wallet',
    triggeredAt: new Date(Date.now() - 120000).toISOString(),
    read: false,
  },
  {
    id: '2',
    type: 'trade',
    title: 'Signal spike',
    message: 'PHRN risk increased to 91 — possible rug pattern',
    triggeredAt: new Date(Date.now() - 300000).toISOString(),
    read: false,
  },
]

export function generateChartData(points = 48) {
  let price = 0.0005 + Math.random() * 0.001
  return Array.from({ length: points }, (_, i) => {
    price *= 1 + (Math.random() - 0.48) * 0.08
    return {
      time: new Date(Date.now() - (points - i) * 300000).toISOString(),
      price,
      volume: Math.random() * 50000,
    }
  })
}
